layout: "main"
logger: "file"
appname: "jitterbug"

builds_per_feed: 5
template: "xslate"
engines:
  xslate:
    path:
        - "/"
    type: text
    cache: 0

jitterbug:
  reports:
    dir: /tmp/jitterbug
  build:
    dir: /tmp/build
  build_process:
    builder: ./scripts/capsule.sh
    builder_variables:
    on_failure: ./scripts/build-failed.sh
    on_failure_to_email:
    on_failure_cc_email: alice@example.com
    on_failure_from_email: donotreply@example.com
    on_failure_subject_prefix: "[jitterbug] FAIL "
    on_failure_header:
    on_failure_footer:
    on_pass: ./scripts/build-pass.sh
    on_pass_to_email:
    on_pass_cc_email: alice@example.com
    on_pass_subject_prefix: "[jitterbug] PASS "
    on_pass_from_email: donotreply@example.com
    on_pass_header:
    on_pass_footer:
    reuse_repo:    1
  options:
    perlbrew: 1
    email_on_pass: 0

plugins:
  DBIC:
    schema:
      dsn: dbi:SQLite:dbname=jitterbug.db
      schema_class: "jitterbug::Schema"
      skip_automake: 1


