layout: "main"
logger: "file"
appname: "jitterbug"

builds_per_feed: 5
template: "xslate"
engines:
  xslate:
    path: /
    type: text
    cache: 0

jitterbug:
  reports:
    dir: /home/jitterbug/reports
  build:
    dir: /home/co/jitterbug/
  build_process:
    reuse_repo: 1
    builder: capsule.sh
    builder_variables:
    from_email: donotreply@replaceme.com
    send_email_to_committer: 0
    on_failure: 1
    on_failure_to_email: devteam@replaceme.com
    on_failure_cc_email:
    on_failure_subject_prefix: "[jitterbug] FAIL "
    on_failure_header:
    on_failure_footer:
    on_pass: 0
    on_pass_to_email: devteam@replaceme.com
    on_pass_cc_email:
    on_pass_subject_prefix: "[jitterbug] PASS "
    on_pass_header:
    on_pass_footer:
  options:
    perlbrew: 1

plugins:
  DBIC:
    schema:
      skip_automake: 1
      pckg: "jitterbug::Schema"
      connect_info:
        - dbi:SQLite:dbname=jitterbug.db
